# Author: Chenghan Li 

import numpy as np
import pyscf
from pyscf import lib
from pyscf import gto
from pyscf import df
from pyscf import scf
from pyscf import grad
from pyscf.lib import logger
from pyscf.qmmm.pbc import mm_mole
from pyscf.qmmm.itrf import _QMMM, _QMMMGrad
from pyscf import qmmm as qmmm_gas

import scipy

def add_mm_charges(scf_method, atoms_or_coords, a, charges, radii=None, rcut=None, unit=None):
    '''Embedding the one-electron (non-relativistic) potential generated by MM
    point charges into QM Hamiltonian.

    The total energy includes the regular QM energy, the interaction between
    the nuclei in QM region and the MM charges, and the static Coulomb
    interaction between the electron density and the MM charges. The electrostatic
    interactions between reference cell and periodic images are also computed at
    point charge level. It does not include the static Coulomb interactions 
    of the MM point charges, the MM energy, the vdw interaction or other 
    bonding/non-bonding effects between QM region and MM particles.

    Args:
        scf_method : a HF or DFT object

        atoms_or_coords : 2D array, shape (N,3)
            MM particle coordinates
        charges : 1D array
            MM particle charges
        a : 2D array, shape (3,3)
            Lattice vectors

    Kwargs:
        radii : 1D array
            The Gaussian charge distribution radii of MM atoms.
        unit : str
            Bohr, AU, Ang (case insensitive). Default is the same to mol.unit

    Returns:
        Same method object as the input scf_method with modified 1e Hamiltonian

    Note:
        1. if MM charge and X2C correction are used together, function mm_charge
        needs to be applied after X2C decoration (.x2c method), eg
        mf = mm_charge(scf.RHF(mol).x2c()), [(0.5,0.6,0.8)], [-0.5]).
        2. Once mm_charge function is applied on the SCF object, it
        affects all the post-HF calculations eg MP2, CCSD, MCSCF etc

    Examples:

    >>> mol = gto.M(atom='H 0 0 0; F 0 0 1', basis='ccpvdz', verbose=0)
    >>> mf = add_mm_charges(dft.RKS(mol), [(0.5,0.6,0.8)], np.eye(3)*10, [-0.3])
    >>> mf.kernel()
    -99.8152796827866
    '''
    mol = scf_method.mol
    if unit is None:
        unit = mol.unit
    mm_mol = mm_mole.create_mm_mol(atoms_or_coords, a, charges,
                        radii=radii, rcut=rcut, unit=unit)
    return qmmm_for_scf(scf_method, mm_mol)

def qmmm_for_scf(scf_method, mm_mol):
    assert isinstance(scf_method, scf.hf.SCF)

    if isinstance(scf_method, scf.hf.SCF):
        # Avoid to initialize _QMMM twice
        if isinstance(scf_method, _QMMM):
            scf_method.mm_mol = mm_mol
            return scf_method

        method_class = scf_method.__class__

    else:
        if isinstance(scf_method._scf, _QMMM):
            scf_method._scf.mm_mol = mm_mol
            return scf_method

        method_class = scf_method._scf.__class__

    class QMMM(_QMMM, method_class):
        def dump_flags(self, verbose=None):
            method_class.dump_flags(self, verbose)
            logger.info(self, '** Add background charges for %s **',
                        method_class)
            _a = self.mm_mol.lattice_vectors()
            logger.info(self, 'lattice vectors  a1 [%.9f, %.9f, %.9f]', *_a[0])
            logger.info(self, '                 a2 [%.9f, %.9f, %.9f]', *_a[1])
            logger.info(self, '                 a3 [%.9f, %.9f, %.9f]', *_a[2])
            if self.verbose >= logger.DEBUG:
                logger.debug(self, 'Charge      Location')
                coords = self.mm_mol.atom_coords()
                charges = self.mm_mol.atom_charges()
                for i, z in enumerate(charges):
                    logger.debug(self, '%.9g    %s', z, coords[i])
            return self

        def get_mm_ewald_pot(self, mol, mm_mol):
            return self.mm_mol.get_ewald_pot(
                mol.atom_coords(),
                mm_mol.atom_coords(), mm_mol.atom_charges())

        def get_qm_ewald_pot(self, mol, dm):
            # d^2 Epbc / dq_i dq_j
            self.qm_ewald_hess = self.mm_mol.get_ewald_pot(mol.atom_coords())
            Q = self.get_qm_charges(dm)
            return lib.einsum('ij,j->i', self.qm_ewald_hess, Q)

        def get_qm_charges(self, dm):
            aoslices = self.mol.aoslice_by_atom()
            chg = self.mol.atom_charges()
            dmS = lib.dot(dm, self.get_ovlp())
            qm_charges = list()
            for iatm in range(self.mol.natm):
                p0, p1 = aoslices[iatm, 2:]
                qm_charges.append(chg[iatm] - np.trace(dmS[p0:p1, p0:p1]))
            return np.asarray(qm_charges)

        def get_vdiff(self, mol, ewald_pot):
            '''
            vdiff_uv = d Q_I / d dm_uv ewald_pot_I
            '''
            vdiff = np.zeros((mol.nao, mol.nao))
            ovlp = self.get_ovlp()
            aoslices = mol.aoslice_by_atom()
            for iatm in range(mol.natm):
                v = ewald_pot[iatm] / 2
                p0, p1 = aoslices[iatm, 2:]
                vdiff[p0:p1] -= v * ovlp[p0:p1]
                vdiff[:,p0:p1] -= v * ovlp[:,p0:p1]
            return vdiff

        def get_veff(self, mol=None, dm=None, dm_last=0, vhf_last=0, hermi=1,
                     mm_ewald_pot=None, qm_ewald_pot=None):
            if mol is None:
                mol = self.mol
            mm_mol = self.mm_mol

            if mm_ewald_pot is None:
                if self.mm_ewald_pot is not None:
                    mm_ewald_pot = self.mm_ewald_pot
                else:
                    mm_ewald_pot = self.get_mm_ewald_pot(mol, mm_mol)
                    self.mm_ewald_pot = mm_ewald_pot
            if qm_ewald_pot is None:
                if self.qm_ewald_hess is not None:
                    qm_ewald_pot = lib.einsum('ij,j->i',
                                    self.qm_ewald_hess, self.get_qm_charges(dm))
                else:
                    qm_ewald_pot = self.get_qm_ewald_pot(mol, dm)

            ewald_pot = mm_ewald_pot + qm_ewald_pot
            vdiff = self.get_vdiff(mol, ewald_pot)

            veff = method_class.get_veff(self, mol, dm, dm_last, vhf_last, hermi)
            if isinstance(veff, lib.NPArrayWithTag):
                metadata = veff.__dict__
                veff = lib.tag_array(veff + vdiff, veff_rs=veff, **metadata)
            else:
                veff = lib.tag_array(veff + vdiff, veff_rs=veff)
            return veff

        def energy_elec(self, dm=None, h1e=None, vhf=None):
            if vhf is None:
                # use the original veff to compute energy
                vhf = method_class.get_veff(self, self.mol, dm)
                return method_class.energy_elec(self, dm=dm, h1e=h1e, vhf=vhf)
            else:
                return method_class.energy_elec(self, dm=dm, h1e=h1e, vhf=vhf.veff_rs)

        def energy_ewald(self, dm=None, mm_ewald_pot=None, qm_ewald_pot=None):
            # QM-QM and QM-MM pbc correction
            if mm_ewald_pot is None:
                if self.mm_ewald_pot is not None:
                    mm_ewald_pot = self.mm_ewald_pot
                else:
                    mm_ewald_pot = self.get_mm_ewald_pot(self.mol, self.mm_mol)
            if qm_ewald_pot is None:
                if self.qm_ewald_hess is not None:
                    qm_ewald_pot = lib.einsum('ij,j->i',
                                    self.qm_ewald_hess, self.get_qm_charges(dm))
                else:
                    qm_ewald_pot = self.get_qm_ewald_pot(self.mol, dm)
            ewald_pot = mm_ewald_pot + qm_ewald_pot / 2
            return ewald_pot @ self.get_qm_charges(dm)

        def energy_nuc(self):
            # gas phase nuc energy
            nuc = self.mol.energy_nuc()
            coords = self.mm_mol.atom_coords()
            charges = self.mm_mol.atom_charges()
            for j in range(self.mol.natm):
                q2, r2 = self.mol.atom_charge(j), self.mol.atom_coord(j)
                r = lib.norm(r2-coords, axis=1)
                nuc += q2*(charges/r).sum()
            return nuc

        def energy_tot(self, dm=None, h1e=None, vhf=None, mm_ewald_pot=None, qm_ewald_pot=None):
            nuc = self.energy_nuc()
            ewald = self.energy_ewald(dm=dm, mm_ewald_pot=mm_ewald_pot, qm_ewald_pot=qm_ewald_pot)
            e_tot = self.energy_elec(dm, h1e, vhf)[0] + nuc + ewald
            self.scf_summary['nuc'] = nuc.real
            self.scf_summary['ewald'] = ewald
            return e_tot

        def nuc_grad_method(self):
            scf_grad = method_class.nuc_grad_method(self)
            return qmmm_grad_for_scf(scf_grad)

    if isinstance(scf_method, scf.hf.SCF):
        qmmm = qmmm_gas.itrf.qmmm_for_scf(scf_method, mm_mol)
        obj2return = qmmm
    else:
        obj2return = qmmm_gas.itrf.qmmm_for_scf(scf_method._scf, mm_mol)
        qmmm = obj2return._scf

    qmmm.mm_mol = mm_mol
    qmmm.mm_ewald_pot = None
    qmmm.qm_ewald_hess = None
    qmmm._keys.update(['mm_mol'])
    qmmm._keys.update(['mm_ewald_pot'])
    qmmm._keys.update(['qm_ewald_hess'])
    qmmm.__class__.dump_flags = QMMM.dump_flags
    qmmm.__class__.get_mm_ewald_pot = QMMM.get_mm_ewald_pot
    qmmm.__class__.get_qm_ewald_pot = QMMM.get_qm_ewald_pot
    qmmm.__class__.get_qm_charges = QMMM.get_qm_charges
    qmmm.__class__.get_vdiff = QMMM.get_vdiff
    qmmm.__class__.get_veff = QMMM.get_veff
    qmmm.__class__.energy_elec = QMMM.energy_elec
    qmmm.__class__.energy_ewald = QMMM.energy_ewald
    qmmm.__class__.energy_nuc = QMMM.energy_nuc
    qmmm.__class__.energy_tot = QMMM.energy_tot
    qmmm.__class__.nuc_grad_method = QMMM.nuc_grad_method
    qmmm.__class__.Gradients = QMMM.nuc_grad_method

    return obj2return

def add_mm_charges_grad(scf_grad, atoms_or_coords, a, charges, radii=None, unit=None):
    '''Apply the MM charges in the QM gradients' method.  It affects both the
    electronic and nuclear parts of the QM fragment.

    Args:
        scf_grad : a HF or DFT gradient object (grad.HF or grad.RKS etc)
            Once the add_mm_charges_grad was applied, it affects all post-HF
            calculations eg MP2, CCSD, MCSCF etc
        coords : 2D array, shape (N,3)
            MM particle coordinates
        charges : 1D array
            MM particle charges
        a : 2D array, shape (3,3)
            Lattice vectors
    Kwargs:
        radii : 1D array
            The Gaussian charge distribution radii of MM atoms.
        unit : str
            Bohr, AU, Ang (case insensitive). Default is the same to mol.unit

    Returns:
        Same gradeints method object as the input scf_grad method
    '''
    assert (isinstance(scf_grad, grad.rhf.Gradients))
    mol = scf_grad.mol
    if unit is None:
        unit = mol.unit
    mm_mol = mm_mole.create_mm_mol(atoms_or_coords, a, charges,
                                   radii=radii, unit=unit)
    mm_grad = qmmm_grad_for_scf(scf_grad)
    mm_grad.base.mm_mol = mm_mol
    return mm_grad

# Define method mm_charge_grad for backward compatibility
mm_charge_grad = add_mm_charges_grad

def qmmm_grad_for_scf(scf_grad):
    '''Add the potential of MM particles to SCF (HF and DFT) object and then
    generate the corresponding QM/MM gradients method for the QM system.
    '''
    if getattr(scf_grad.base, 'with_x2c', None):
        raise NotImplementedError('X2C with QM/MM charges')

    # Avoid to initialize _QMMMGrad twice
    if isinstance(scf_grad, _QMMMGrad):
        return scf_grad

    assert (isinstance(scf_grad.base, scf.hf.SCF) and
           isinstance(scf_grad.base, _QMMM))

    grad_class = scf_grad.__class__
    class QMMM(_QMMMGrad, grad_class):
        def dump_flags(self, verbose=None):
            grad_class.dump_flags(self, verbose)
            logger.info(self, '** Add background charges for %s **', grad_class)
            _a = self.base.mm_mol.lattice_vectors()
            logger.info(self, 'lattice vectors  a1 [%.9f, %.9f, %.9f]', *_a[0])
            logger.info(self, '                 a2 [%.9f, %.9f, %.9f]', *_a[1])
            logger.info(self, '                 a3 [%.9f, %.9f, %.9f]', *_a[2])
            if self.verbose >= logger.DEBUG1:
                logger.debug1(self, 'Charge      Location')
                coords = self.base.mm_mol.atom_coords()
                charges = self.base.mm_mol.atom_charges()
                for i, z in enumerate(charges):
                    logger.debug1(self, '%.9g    %s', z, coords[i])
            return self

        def grad_ewald(self, dm=None, with_mm=False, mm_ewald_pot=None, qm_ewald_pot=None):
            # pbc correction grad w.r.t. qm and mm atom positions
            if dm is None: dm = self.base.make_rdm1()
            mol = self.base.mol
            cell = self.base.mm_mol
            assert cell.dimension == 3
            qm_charges = self.base.get_qm_charges(dm)
            qm_coords = self.base.mol.atom_coords()
            mm_charges = self.base.mm_mol.atom_charges()
            mm_coords = self.base.mm_mol.atom_coords()

            qm_charge_grad = np.zeros_like(qm_coords)
            if mm_ewald_pot is None:
                if self.base.mm_ewald_pot is not None:
                    mm_ewald_pot = self.base.mm_ewald_pot
                else:
                    mm_ewald_pot = self.base.get_mm_ewald_pot(mol, cell)
            if qm_ewald_pot is None:
                if self.base.qm_ewald_hess is not None:
                    qm_ewald_pot = lib.einsum('ij,j->i',
                                    self.base.qm_ewald_hess, qm_charges)
                else:
                    qm_ewald_pot = self.base.get_qm_ewald_pot(mol, dm)
            ewald_pot = mm_ewald_pot + qm_ewald_pot
            aoslices = mol.aoslice_by_atom()
            dEds = np.zeros((mol.nao, mol.nao))
            for iatm in range(mol.natm):
                v = ewald_pot[iatm] / 2
                p0, p1 = aoslices[iatm, 2:]
                dEds[p0:p1] -= v * dm[p0:p1]
                dEds[:,p0:p1] -= v * dm[:,p0:p1]
            s1 = self.get_ovlp(mol)
            for iatm in range(mol.natm):
                p0, p1 = aoslices[iatm, 2:]
                qm_charge_grad[iatm] += \
                    lib.einsum('xij,ij->x', s1[:,p0:p1], dEds[p0:p1]) * 2

            ew_eta, ew_cut = cell.get_ewald_params()
            Lall = cell.get_lattice_Ls()

            def loop(i):
                for j in range(len(qm_coords)):
                    if j == i:
                        continue
                    else:
                        yield j, qm_charges[j], qm_coords[j], False
                for j in range(len(mm_coords)):
                    yield j, mm_charges[j], mm_coords[j], True

            qm_ewovrl_grad = np.zeros_like(qm_coords)
            mm_ewovrl_grad = np.zeros_like(mm_coords)
            for i, qi in enumerate(qm_charges):
                ri = qm_coords[i]
                for j, qj, rj, is_mm in loop(i):
                    r1 = ri-rj + Lall
                    r = np.sqrt(np.einsum('ji,ji->j', r1, r1))
                    r = r.reshape(len(r),1)
                    grad_i = np.sum(+ (qi * qj / r ** 3 * r1 *
                                    scipy.special.erf(ew_eta * r).reshape(len(r),1)), axis = 0) + \
                             np.sum(- qi * qj / r ** 2 * r1 * 2 * ew_eta / np.sqrt(np.pi) *
                                 np.exp(-ew_eta**2 * r ** 2).reshape(len(r),1), axis = 0)
                    qm_ewovrl_grad[i] += grad_i
                    if is_mm and with_mm:
                        mm_ewovrl_grad[j] -= grad_i

            mesh = cell.mesh
            Gv, Gvbase, weights = cell.get_Gv_weights(mesh)
            absG2 = lib.einsum('gi,gi->g', Gv, Gv)
            absG2[absG2==0] = 1e200
            qm_SI = cell.get_SI(Gv, coords=qm_coords)
            mm_SI = cell.get_SI(Gv, coords=mm_coords)
            qm_ZSI = lib.einsum('i,ig->g', qm_charges, qm_SI)
            mm_ZSI = lib.einsum('i,ig->g', mm_charges, mm_SI)
            tot_ZSI = mm_ZSI + qm_ZSI
            coulG = 4*np.pi / absG2
            coulG *= weights
            ZexpG2 = coulG * np.exp(-absG2/(4*ew_eta**2))
            ZexpG2_mod = ZexpG2.reshape(len(ZexpG2),1) * Gv # Ngrid x 3
            qm_ewg_grad = -np.imag(lib.dot(qm_charges.reshape(-1,1) * qm_SI.conj(), tot_ZSI.reshape(-1,1) * ZexpG2_mod))
            if with_mm:
                mm_ewg_grad = -np.imag(lib.dot(mm_charges.reshape(-1,1) * mm_SI.conj(), qm_ZSI.reshape(-1,1) * ZexpG2_mod))
                return qm_ewg_grad + qm_ewovrl_grad + qm_charge_grad, mm_ewg_grad + mm_ewovrl_grad
            else:
                return qm_ewg_grad + qm_ewovrl_grad + qm_charge_grad

        def _finalize(self):
            g_ewald_qm, self.de_ewald_mm = self.grad_ewald(with_mm=True)
            self.de += g_ewald_qm
            grad_class._finalize(self)

    qmmm = qmmm_gas.itrf.qmmm_grad_for_scf(scf_grad)
    qmmm.de_ewald_mm = None
    qmmm._keys.update(['de_ewald_mm'])
    qmmm.__class__.dump_flags = QMMM.dump_flags
    qmmm.__class__.grad_ewald = QMMM.grad_ewald
    qmmm.__class__._finalize = QMMM._finalize
    return qmmm
